# Generated by Django 4.2.7 on 2026-05-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_is_verified_doctor_license_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='address_line1',
            field=models.CharField(blank=True, help_text='Street address', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='address_line2',
            field=models.CharField(blank=True, help_text='Area/Landmark', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_mode',
            field=models.CharField(choices=[('in_person', 'In-Person Only'), ('online', 'Online Only'), ('both', 'Both In-Person & Online')], default='both', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital_name',
            field=models.CharField(blank=True, help_text='Hospital/Clinic name', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_days',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='slot_duration',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='state_council',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
