# Generated by Django 4.2.7 on 2026-05-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_address_line1_doctor_address_line2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='consultation_mode',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='hospital_name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_name',
            field=models.CharField(blank=True, help_text='Hospital/Clinic name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_type',
            field=models.CharField(choices=[('in_person', 'In-Person'), ('online', 'Online'), ('both', 'Both In-Person & Online')], default='both', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_days',
            field=models.CharField(blank=True, help_text='Comma separated days', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Consultation end time', null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Consultation start time', null=True),
        ),
    ]
